// <auto-generated />
using System;
using AssemblersApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AssemblersApi.Migrations
{
    [DbContext(typeof(AssemblersDbContext))]
    [Migration("20251005090951_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AssemblersApi.Models.Assembler", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AverageRating")
                        .HasColumnType("decimal(3,2)");

                    b.Property<string>("CoverImage")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Assemblers");
                });

            modelBuilder.Entity("AssemblersApi.Models.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssemblerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AssemblerId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ServiceId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("AssemblersApi.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e89cb5ed-4318-45f9-b5bf-799f08fd1919"),
                            CreatedAt = new DateTime(2025, 10, 5, 9, 9, 51, 352, DateTimeKind.Utc).AddTicks(7520),
                            Description = "Electronic device assembly and repair",
                            Image = "electronics.jpg",
                            Name = "Electronics",
                            UpdatedAt = new DateTime(2025, 10, 5, 9, 9, 51, 352, DateTimeKind.Utc).AddTicks(7520)
                        },
                        new
                        {
                            Id = new Guid("17f4bfd9-b1c2-4917-9f6f-ce7c360f4ba7"),
                            CreatedAt = new DateTime(2025, 10, 5, 9, 9, 51, 352, DateTimeKind.Utc).AddTicks(8160),
                            Description = "Furniture assembly and repair",
                            Image = "furniture.jpg",
                            Name = "Furniture",
                            UpdatedAt = new DateTime(2025, 10, 5, 9, 9, 51, 352, DateTimeKind.Utc).AddTicks(8160)
                        },
                        new
                        {
                            Id = new Guid("815854be-cba7-4e3c-b1c3-92fe21b1e1c5"),
                            CreatedAt = new DateTime(2025, 10, 5, 9, 9, 51, 352, DateTimeKind.Utc).AddTicks(8170),
                            Description = "Home improvement and maintenance",
                            Image = "home-improvement.jpg",
                            Name = "Home Improvement",
                            UpdatedAt = new DateTime(2025, 10, 5, 9, 9, 51, 352, DateTimeKind.Utc).AddTicks(8170)
                        },
                        new
                        {
                            Id = new Guid("2db12c9c-19d6-4ed8-8745-f5ddc5fdbcc9"),
                            CreatedAt = new DateTime(2025, 10, 5, 9, 9, 51, 352, DateTimeKind.Utc).AddTicks(8180),
                            Description = "Computer assembly and repair",
                            Image = "computer-services.jpg",
                            Name = "Computer Services",
                            UpdatedAt = new DateTime(2025, 10, 5, 9, 9, 51, 352, DateTimeKind.Utc).AddTicks(8180)
                        },
                        new
                        {
                            Id = new Guid("5071b1d1-2e4a-4ecf-955a-2ba4ccc4bb93"),
                            CreatedAt = new DateTime(2025, 10, 5, 9, 9, 51, 352, DateTimeKind.Utc).AddTicks(8180),
                            Description = "Home appliance repair and maintenance",
                            Image = "appliance-repair.jpg",
                            Name = "Appliance Repair",
                            UpdatedAt = new DateTime(2025, 10, 5, 9, 9, 51, 352, DateTimeKind.Utc).AddTicks(8180)
                        });
                });

            modelBuilder.Entity("AssemblersApi.Models.DayAvailability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssemblerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Available")
                        .HasColumnType("bit");

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("End")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Start")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("AssemblerId");

                    b.ToTable("DayAvailabilities");
                });

            modelBuilder.Entity("AssemblersApi.Models.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssemblerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BookingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AssemblerId");

                    b.HasIndex("BookingId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("AssemblersApi.Models.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssemblerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("AverageRating")
                        .HasColumnType("decimal(3,2)");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("ReviewCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AssemblerId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("AssemblersApi.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ProfileImage")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("customer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("da0ee40f-1978-4412-82ee-87fb0a66bc11"),
                            CreatedAt = new DateTime(2025, 10, 5, 9, 9, 51, 353, DateTimeKind.Utc).AddTicks(2530),
                            Email = "john@example.com",
                            Name = "John Doe",
                            Password = "hashedpassword",
                            Role = "customer",
                            UpdatedAt = new DateTime(2025, 10, 5, 9, 9, 51, 353, DateTimeKind.Utc).AddTicks(2660)
                        });
                });

            modelBuilder.Entity("AssemblersApi.Models.Assembler", b =>
                {
                    b.HasOne("AssemblersApi.Models.User", "User")
                        .WithMany("AssemblerProfiles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AssemblersApi.Models.Booking", b =>
                {
                    b.HasOne("AssemblersApi.Models.Assembler", "Assembler")
                        .WithMany("Bookings")
                        .HasForeignKey("AssemblerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AssemblersApi.Models.User", "Customer")
                        .WithMany("CustomerBookings")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AssemblersApi.Models.Service", "Service")
                        .WithMany("Bookings")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Assembler");

                    b.Navigation("Customer");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("AssemblersApi.Models.DayAvailability", b =>
                {
                    b.HasOne("AssemblersApi.Models.Assembler", "Assembler")
                        .WithMany("Availability")
                        .HasForeignKey("AssemblerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assembler");
                });

            modelBuilder.Entity("AssemblersApi.Models.Review", b =>
                {
                    b.HasOne("AssemblersApi.Models.Assembler", "Assembler")
                        .WithMany("Reviews")
                        .HasForeignKey("AssemblerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AssemblersApi.Models.Booking", "Booking")
                        .WithMany("Reviews")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AssemblersApi.Models.User", "Customer")
                        .WithMany("ReviewsGiven")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Assembler");

                    b.Navigation("Booking");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("AssemblersApi.Models.Service", b =>
                {
                    b.HasOne("AssemblersApi.Models.Assembler", "Assembler")
                        .WithMany("Services")
                        .HasForeignKey("AssemblerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AssemblersApi.Models.Category", "Category")
                        .WithMany("Services")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Assembler");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("AssemblersApi.Models.Assembler", b =>
                {
                    b.Navigation("Availability");

                    b.Navigation("Bookings");

                    b.Navigation("Reviews");

                    b.Navigation("Services");
                });

            modelBuilder.Entity("AssemblersApi.Models.Booking", b =>
                {
                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("AssemblersApi.Models.Category", b =>
                {
                    b.Navigation("Services");
                });

            modelBuilder.Entity("AssemblersApi.Models.Service", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("AssemblersApi.Models.User", b =>
                {
                    b.Navigation("AssemblerProfiles");

                    b.Navigation("CustomerBookings");

                    b.Navigation("ReviewsGiven");
                });
#pragma warning restore 612, 618
        }
    }
}
